image: redmic/maven-gitlab

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

deploy:
  script:
    - mvn $MAVEN_CLI_OPTS deploy
